---
title: "Analyse"
---

<h2>5.1 Ausgangspunkt der Analyse</h2>

<p>Die Theorie hat bereits die Bausteine festgelegt, die das spätere Modell benötigt. Dazu gehören die Verarbeitung von Zeitreihen, Renditeberechnungen, Volatilität, Drawdown, Sharpe Ratio, Korrelation, Portfoliorisiko, Rebalancing, Buy-and-Hold und eine Trendfolgestrategie. Die Methodik verlangt ausserdem einen vergleichbaren Zeitabschnitt, dasselbe Startkapital, die Reinvestition der Dividenden und eine einheitliche Datenfrequenz. Beim 60/40-Portfolio ist ein jährliches Rebalancing vorgesehen.</p>

<p>Damit besteht meine Aufgabe in der Analyse nicht darin, eine völlig neue Finanztheorie zu entwickeln. Ich muss die bereits beschriebenen Bestandteile so zusammenführen, dass sie mit realen historischen Daten reproduzierbar ausgeführt werden können.</p>

<p>Dabei unterscheide ich zwei Ebenen:<br>
1. <strong>Das allgemeine System:</strong> Es soll verschiedene geeignete Datensätze und Parameter verarbeiten können.<br>
2. <strong>Die Untersuchung der Maturarbeit:</strong> Sie verwendet später eine feste und begründete Auswahl von Daten und Parametern.</p>

<p>Diese Trennung ist wichtig, weil die spätere Benutzeroberfläche dieselbe Engine mit anderen Eingaben verwenden können soll. Für die wissenschaftliche Auswertung werden die Parameter dagegen vor dem Hauptlauf festgelegt und nicht nachträglich so verändert, dass ein günstigeres Resultat entsteht. Das entspricht auch der im Theorieteil behandelten Gefahr von Data Snooping und Overfitting [@hilpischPythonFinanceMastering2019, S. 697; @kommerSouveraenInvestierenMit2025, S. 607–608].</p>

<h2>5.2 Reihenfolge der technischen Entwicklung</h2>
<p>Aus den Anforderungen ergibt sich für mich folgende Reihenfolge:</p>

$$
\begin{array}{c}
\boxed{\text{\Large 1. Internes Datenformat festlegen}}
\\[0.4cm]
\downarrow
\\[0.4cm]
\boxed{\text{\Large 2. Datenquellen auf dieses Format abbilden}}
\\[0.4cm]
\downarrow
\\[0.4cm]
\boxed{\text{\Large 3. Import, Normalisierung und Validierung definieren}}
\\[0.4cm]
\downarrow
\\[0.4cm]
\boxed{\text{\Large 4. Veränderbare Einstellungen des Systems festlegen}}
\\[0.4cm]
\downarrow
\\[0.4cm]
\boxed{\text{\Large 5. Einheitlichen Ergebnisvertrag festlegen}}
\\[0.4cm]
\downarrow
\\[0.4cm]
\boxed{\text{\Large 6. Leeres Grundgerüst der Engine definieren}}
\\[0.4cm]
\downarrow
\\[0.4cm]
\boxed{\text{\Large 7. Vorhandene Funktionen integrieren}}
\end{array}
$$

<p>Die Reihenfolge ist bewusst so gewählt. Würde ich zuerst die Simulationsfunktion programmieren und erst danach entscheiden, welche Eingaben und Ausgaben sie besitzen soll, würden Datenformat, Strategien und Benutzeroberfläche unnötig voneinander abhängig.</p>
<p>Die konkrete Reihenfolge ist meine eigene Designentscheidung. Die Quellen liefern die Grundlagen dafür, welche Datenstrukturen und Finanzinformationen benötigt werden; sie schreiben nicht diese exakte Softwarearchitektur vor.</p>

<h2>5.3 Entwicklung eines einheitlichen Datenformats</h2>
<h3>5.3.1 Warum überhaupt ein eigenes internes Format?</h3>
<p>Die später verwendeten Daten können aus unterschiedlichen Quellen stammen. Yahoo Finance liefert Marktzeitreihen anders als FRED eine Zinsreihe oder eine Makrodatenbank jährliche BIP-Werte. Würde jede Strategie direkt mit dem Format einer bestimmten Quelle arbeiten, müsste sich auch die Strategie ändern, sobald der Anbieter gewechselt wird.</p>
<p>Deshalb erhält das Modell einen <strong>anbieterunabhängigen Datenvertrag</strong>. Ein Importmodul ist dafür verantwortlich, Quelldaten in diesen Vertrag zu übersetzen. Die eigentliche Strategie sieht danach nur noch standardisierte Daten.</p>
<p>Wes McKinney beschreibt Datenanalyse als Abfolge von Einlesen, Bereinigen, Kombinieren, Normalisieren, Umformen und anschliessender Berechnung. Er behandelt dabei sowohl tabellarische Daten als auch Zeitreihen und zeigt, dass pandas gerade für solche strukturierten Daten entwickelt wurde [@mckinneyPythonDataAnalysis2022]. Diese Grundidee passt zu meiner Untersuchung: Die Quelle darf unterschiedlich sein, die Berechnung soll danach aber auf einer einheitlichen Struktur stattfinden.</p>
<p>Die Entscheidung, dafür einen eigenen Datenvertrag zu definieren, ist meine technische Schlussfolgerung aus diesem Bedarf.</p>

<h3>5.3.2 Warum CSV als Austauschformat?</h3>
<p>Für den Austausch zwischen Import, Kontrolle und späterer Benutzeroberfläche verwende ich in der ersten Version CSV-Dateien. McKinney behandelt in Kapitel 6 das Einlesen tabellarischer Textdaten und verwendet <code>pandas.read_csv()</code> als eines der zentralen Werkzeuge für solche Daten [@mckinneyPythonDataAnalysis2022].</p>
<p>CSV ist für mein Projekt nicht deshalb ausgewählt, weil es allen anderen Formaten technisch überlegen wäre. Die Gründe sind praktischer:</p>

- Die Datei kann direkt mit einem Texteditor, Tabellenprogramm oder Python geöffnet werden.
- Beim Entwickeln kann ich leicht kontrollieren, ob ein Adapter tatsächlich die erwarteten Spalten erzeugt.
- Eine spätere Weboberfläche kann eine CSV-Datei einfach als Benutzereingabe akzeptieren.
- pandas kann das Format ohne zusätzliche Spezialbibliothek einlesen.

<p>CSV besitzt gleichzeitig Grenzen. Datentypen und die Bedeutung einer Spalte werden nicht ausreichend durch die Datei selbst erklärt. Darum genügt eine CSV allein nicht: Das System benötigt zusätzlich einen klar definierten Datenvertrag und Metadaten.</p>
<p>Für die interne Berechnung bleibt die Datei nicht als Textstruktur bestehen. Nach dem Einlesen wird sie in pandas-Objekte überführt.</p>

<h3>5.3.3 Warum ein Long-Format?</h3>
<p>Für die Marktzeitreihen verwende ich als Austauschformat eine lange Tabelle. Eine Beobachtung besteht aus einem Datum, einer Anlagenkennung und einem Wert.</p>
<p>McKinney beschreibt im Abschnitt "Pivoting 'Long' to 'Wide' Format" ausdrücklich, dass mehrere Zeitreihen häufig in einem sogenannten <i>long</i> beziehungsweise <i>stacked format</i> gespeichert werden. In diesem Format stellt jede einzelne Beobachtung eine eigene Zeile dar. Er zeigt danach mit <code>DataFrame.pivot()</code>, wie dieselben Daten für Berechnungen in eine breite Tabelle mit einer Spalte pro Zeitreihe umgeformt werden können [@mckinneyPythonDataAnalysis2022].</p>
<p>Diese Beschreibung passt direkt zu meinem Problem. Für ein allgemeines Eingabeformat ist Long praktisch, weil eine neue Anlage zusätzliche Zeilen erzeugt, ohne dass sich die Grundstruktur der Tabelle ändert. Für bestimmte Berechnungen ist dagegen eine breite Darstellung komfortabler. Deshalb lege ich nicht fest, dass jede Stufe des Systems Long sein muss:</p>

$$
\begin{array}{c}
\text{\large \textbf{Austausch / Speicherung:}}
\\[4pt]
\boxed{\texttt{date \;|\; asset\_id \;|\; performance\_value}}
\\[10pt]
\downarrow
\\[-2pt]
\text{\texttt{pandas pivot()}}
\\[10pt]
\downarrow
\\[-2pt]
\text{\large \textbf{Interne Berechnung:}}
\\[4pt]
\boxed{\texttt{date \;|\; ASSET\_A \;|\; ASSET\_B \;|\; ASSET\_C \;|\; \ldots}}
\end{array}
$$

<p>McKinney liefert die nachvollziehbare Grundlage dafür, dass Long ein gebräuchliches Format für mehrere Zeitreihen ist und sich mit pandas eindeutig in Wide umformen lässt. Meine Entscheidung ist, Long deshalb als äussere Schnittstelle und Wide dort zu verwenden, wo die Berechnung davon profitiert.</p>

<h3>5.3.4 Marktzeitreihen: minimaler Datenvertrag</h3>

<p>Für eine Marktzeitreihe definiere ich zunächst drei Pflichtfelder:</p>

$$
\begin{array}{|l|l|}
\hline
\textbf{Feld} & \textbf{Bedeutung} \\
\hline
\texttt{date} & \text{Datum der Beobachtung} \\
\hline
\texttt{asset\_id} & \text{interne, anbieterunabhängige Kennung der Anlage} \\
\hline
\texttt{performance\_value} & \text{Wertreihe, aus der die Performance berechnet werden darf} \\
\hline
\end{array}
$$

<p>Optional kann eine vierte Spalte vorhanden sein:</p>

$$
\begin{array}{|l|l|}
\hline
\textbf{Feld} & \textbf{Bedeutung} \\
\hline
\texttt{signal\_value} & \text{separate Wertreihe für technische Handelssignale} \\
\hline
\end{array}
$$

<p>Beispiel:</p>

$$
\begin{array}{|c|c|c|c|}
\hline
\textbf{date} & \textbf{asset\_id} & \textbf{performance\_value} & \textbf{signal\_value} \\
\hline
2020\text{-}01\text{-}02 & \texttt{EQ\_DEMO} & 100.0 & 50.25 \\
\hline
2020\text{-}01\text{-}03 & \texttt{EQ\_DEMO} & 102.0 & 51.00 \\
\hline
2020\text{-}01\text{-}02 & \texttt{BD\_DEMO} & 100.0 & 104.80 \\
\hline
2020\text{-}01\text{-}03 & \texttt{BD\_DEMO} & 100.5 & 104.90 \\
\hline
\end{array}
$$

<p><code>asset_id</code> ist bewusst nicht dasselbe wie ein Yahoo-Ticker. Der Ticker gehört zur Quelle; <code>asset_id</code> gehört zum Modell. Dadurch könnte dieselbe logische Anlage später aus einer anderen Quelle importiert werden, ohne dass alle Strategiekonfigurationen angepasst werden müssen.</p>

<p>Auch <code>performance_value</code> ist absichtlich kein Anbieterbegriff wie <code>Adj Close</code>. Der Importadapter muss dokumentieren, welche Quellenspalte auf dieses Feld abgebildet wurde.</p>

In [1]:
from io import StringIO
import pandas as pd

beispiel_csv = "\n".join([
    "date,asset_id,performance_value",
    "2020-01-02,EQ_DEMO,100.0",
    "2020-01-03,EQ_DEMO,102.0",
    "2020-01-06,EQ_DEMO,101.0",
    "2020-01-02,BD_DEMO,100.0",
    "2020-01-03,BD_DEMO,100.5",
    "2020-01-06,BD_DEMO,101.0",
])

markt_long = pd.read_csv(StringIO(beispiel_csv))
markt_long["date"] = pd.to_datetime(markt_long["date"])
markt_long

        date asset_id  performance_value
0 2020-01-02  EQ_DEMO              100.0
1 2020-01-03  EQ_DEMO              102.0
2 2020-01-06  EQ_DEMO              101.0
3 2020-01-02  BD_DEMO              100.0
4 2020-01-03  BD_DEMO              100.5
5 2020-01-06  BD_DEMO              101.0

<p>Für die spätere Portfolioberechnung kann dieselbe Tabelle eindeutig umgeformt werden. Dadurch muss die externe Datei nicht bereits für jede konkrete mathematische Funktion optimiert sein.</p>

In [4]:
markt_wide = (
    markt_long
    .pivot(index="date", columns="asset_id", values="performance_value")
    .sort_index()
    .reset_index()
)
    
markt_wide.columns.name = None
markt_wide

        date  BD_DEMO  EQ_DEMO
0 2020-01-02    100.0    100.0
1 2020-01-03    100.5    102.0
2 2020-01-06    101.0    101.0

<h3>5.3.5 Was bedeutet <code>performance_value</code>?</h3>

<p>Die Spalte <code>performance_value</code> ist die Wertreihe, aus der das Modell später die tatsächliche Wertentwicklung einer Anlage berechnet. Dabei soll nicht einfach irgendein verfügbarer Kurs übernommen werden. Für meine Untersuchung ist entscheidend, dass die gewählte Reihe zur festgelegten Behandlung der Dividenden passt.</p>

<p>Im Theorieteil wurde bereits festgelegt, dass für den langfristigen Vergleich eine Gesamtrendite beziehungsweise ein <i>Total Return</i> geeigneter ist als eine reine Kursbetrachtung. Ein Total Return berücksichtigt neben Kursveränderungen auch laufende Erträge wie Dividenden [@kommerSouveraenInvestierenMit2025, S. 466–467]. Da in meiner Methodik die Reinvestition der Dividenden vorgesehen ist, muss die verwendete Performance-Reihe diese Annahme abbilden.</p>

<p><code>performance_value</code> bezeichnet deshalb bewusst keinen bestimmten Anbieterbegriff. Je nach Datenquelle kann dahinter zum Beispiel ein Total-Return-Index oder eine entsprechend bereinigte Wertreihe stehen. Der jeweilige Import muss dokumentieren, welche ursprüngliche Reihe verwendet wurde.</p>

<p>Dadurch bleibt die Berechnung unabhängig von der Quelle. Die Engine erhält immer dieselbe Spalte, während die Umwandlung davor sicherstellt, dass ihre Bedeutung vergleichbar ist.</p>

<h3>5.3.6 Wozu dient <code>signal_value</code>?</h3>

<p>Für Buy-and-Hold oder ein Rebalancing-Portfolio genügt grundsätzlich die Performance-Reihe. Bei einer technischen Strategie wie der Trendfolge kommt jedoch eine zweite Aufgabe hinzu: Aus einer Kursreihe wird ein Handelssignal berechnet.</p>
<p>Hilpisch verwendet für seine SMA-Strategie zwei gleitende Durchschnitte und leitet daraus eine Long- beziehungsweise Short-Position ab [@hilpischPythonFinanceMastering2019, S. 691–692]. Für meine Untersuchung wurde diese Regel bereits im Theorieteil zu Long/Cash angepasst. Ausserdem wird das Signal um eine Periode verschoben, damit keine bereits bekannte Rendite derselben Periode verwendet wird [@hilpischPythonFinanceMastering2019, S. 694].</p>
<p>Damit das allgemeine System später nicht voraussetzen muss, dass Performance-Berechnung und Signal immer auf exakt derselben Reihe beruhen, kann zusätzlich <code>signal_value</code> angegeben werden. Fehlt diese Spalte, darf die Strategie <code>performance_value</code> nur dann verwenden, wenn dies in der Konfiguration ausdrücklich erlaubt ist.</p>
<p>Für die erste Untersuchung kann sich später herausstellen, dass beide Felder auf dieselbe Reihe zeigen. Die Trennung bleibt trotzdem sinnvoll, weil sie die Datenstruktur nicht auf diese eine Untersuchung beschränkt.</p>

<h3>5.3.7 Metadaten und zusätzliche Datentypen</h3>

<p>Die Marktdatei enthält absichtlich nur die Werte, die sich über die Zeit verändern. Weitere Informationen zu einer Anlage werden separat gespeichert. Dazu gehören beispielsweise Name, Anlageklasse, Währung, Land und ursprüngliche Datenquelle.</p>

<p>Für diese Informationen ist eine Datei <code>assets.csv</code> vorgesehen:</p>

\[
\begin{array}{c|c}
\textbf{Feld} & \textbf{Bedeutung} \\
\hline
\texttt{asset\_id} & \text{Interne, anbieterunabhängige Kennung der Anlage} \\
\texttt{name} & \text{Name der Anlage} \\
\texttt{asset\_class} & \text{Anlageklasse, z.\,B. Aktien oder Anleihen} \\
\texttt{country} & \text{Zugeordnetes Land bzw. Markt} \\
\texttt{currency} & \text{Währung der Anlage} \\
\texttt{provider} & \text{Datenanbieter} \\
\texttt{provider\_symbol} & \text{Symbol bzw. Kennung beim Datenanbieter}
\end{array}
\]

<p>Die interne Kennung <code>asset_id</code> verbindet die Metadaten mit den Marktwerten. Dadurch kann zum Beispiel <code>US_EQUITY</code> im Modell gleich bleiben, auch wenn die Daten später von einem anderen Anbieter bezogen werden.</p>

<p>Nicht alle benötigten Daten sind Marktpreise. Für die Sharpe Ratio wird eine risikofreie Rendite benötigt. Sie muss in derselben Periodenlogik wie die untersuchte Rendite verwendet werden [@kommerSouveraenInvestierenMit2025, S. 165–166]. Dafür ist eine getrennte Datei vorgesehen:</p>

\[
\begin{array}{c|c}
\textbf{Feld} & \textbf{Bedeutung} \\
\hline
\texttt{date} & \text{Datum der Beobachtung} \\
\texttt{series\_id} & \text{Kennung der risikofreien Zinsreihe} \\
\texttt{value} & \text{Beobachteter Zinssatz} \\
\texttt{unit} & \text{Einheit des Wertes}
\end{array}
\]

<p>Auch Makrodaten wie das BIP unterscheiden sich von täglichen Marktzeitreihen. Sie werden deshalb separat gespeichert:</p>

\[
\begin{array}{c|c}
\textbf{Feld} & \textbf{Bedeutung} \\
\hline
\texttt{period} & \text{Zeitraum der Beobachtung} \\
\texttt{country} & \text{Land, auf das sich der Wert bezieht} \\
\texttt{indicator} & \text{Makroökonomischer Indikator} \\
\texttt{value} & \text{Beobachteter Wert} \\
\texttt{unit} & \text{Einheit des Wertes} \\
\texttt{available\_from} & \text{Zeitpunkt, ab dem die Information verfügbar war}
\end{array}
\]

<p>Das zusätzliche Feld <code>available_from</code> soll verhindern, dass ein historischer Backtest einen Jahreswert bereits verwendet, bevor dieser damals verfügbar gewesen wäre. Die genaue Regel dafür wird später bei der BIP-Strategie festgelegt. Sie folgt dem gleichen Grundprinzip wie die im Theorieteil behandelte Vermeidung von Look-ahead Bias [@hilpischPythonFinanceMastering2019, S. 319–321].</p>

<h2>5.4 Datenquellen und Umwandlung</h2>
<h3>5.4.1 Trennung zwischen Datenquelle und Modell</h3>

<p>Nachdem das interne Format festgelegt ist, kann untersucht werden, wie verschiedene Anbieter darauf abgebildet werden. Die Datenquelle soll dabei nicht direkt von einer Strategie aufgerufen werden. Stattdessen übernimmt ein Importmodul die Umwandlung.</p>

\[
\begin{array}{c}
\boxed{\text{Datenquelle}} \\[6pt]
\downarrow \\[6pt]
\boxed{\text{Import und Umwandlung}} \\[6pt]
\downarrow \\[6pt]
\boxed{\text{Einheitliches Datenformat}} \\[6pt]
\downarrow \\[6pt]
\boxed{\text{Simulation}}
\end{array}
\]

<p>Dadurch bleibt die eigentliche Berechnung gleich, auch wenn später eine andere Datenquelle verwendet wird. Für meine Untersuchung sind Yahoo Finance und FRED bereits in der Methodik als mögliche Quellen vorgesehen [@yahooYahooFinanzenDeutschlandBoerse2026; @federalreservebankofst.louisFederalReserveEconomic2026]. Weitere Quellen können später ergänzt werden, solange sie auf dasselbe interne Format abgebildet werden können.</p>

<h3>5.4.2 Marktdaten</h3>

<p>Für Marktzeitreihen soll ein erster Adapter historische Daten eines Anbieters laden und daraus die benötigten Felder erzeugen. Bei Yahoo Finance beziehungsweise einer Python-Schnittstelle wie <code>yfinance</code> muss der Adapter insbesondere festhalten:</p>

- welches Wertpapier geladen wurde,
- welcher Zeitraum verwendet wurde,
- welche Datenfrequenz angefordert wurde,
- welche ursprüngliche Spalte zu <code>performance_value</code> wird,
- welche Reihe für <code>signal_value</code> verwendet wird,
- und wie Dividenden beziehungsweise Splits in den Quelldaten behandelt werden.

<p>Die technische Umbenennung einer Spalte reicht damit nicht aus. Zuerst muss geklärt sein, was die ursprüngliche Reihe tatsächlich bedeutet. Für konkrete Parameter einer später verwendeten API soll bei der Implementierung zusätzlich deren direkte technische Dokumentation verwendet werden.</p>